# frozen_string_literal: true

ruby "~> 2.6.0"

gem 'asciidoctor', '~> 2.0.12'
gem 'asciidoctor-pdf', '~> 1.5.4'
gem 'asciidoctor-pdf-cjk', '~> 0.1.3'
gem 'asciidoctor-pdf-cjk-kai_gen_gothic', '~> 0.1.1'
gem 'asciidoctor-diagram', '~> 2.1.1'
gem 'rake', '~> 13.0.3'
